### ISSUE TITLE
EPIPE error on login

### ISSUE THREAD

**Issue by russjohnson09** [russjohnson09/coderuss#65]
info: .. root=..
info: /coderuss/nodeserver/../.apt/usr/games/frotz
info: /usr/games/frotz frotz=/usr/games/frotz
info: creating logsene transport
info: setting up morgan logging to winston
info: console_log_level:info
info: main application listening on port: 31001
server listening on port 3000
info: started routing for /v1/zork
info: [{"server_start":1488460487406,"_id":"58b81ac7e1f454037e07be38"}]
server clientError { Error: write EPIPE
    at exports._errnoException (util.js:1007:11)
    at WriteWrap.afterWrite (net.js:793:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
server clientError { Error: write EPIPE
    at exports._errnoException (util.js:1007:11)
    at WriteWrap.afterWrite (net.js:793:14) code: 'EPIPE', errno: 'EPIPE', syscall: 'write'

**Comment by russjohnson09** [comment]
broken socket-io cdn on the client side breaks tests.
